### ISSUE TITLE
CLI raises an exception before it can generate the available commands

### ISSUE THREAD

**Issue by ryankwilliams** [rhpit/manageiq-cli#60]
After pulling the latest changes, I got a problem when trying to run the CLI to view the available commands outside my local copy of the project. I now get an exception.

Steps to reproduce the problem:
```bash
# 1. create virtual environment 
$ virtualenv miqcli && source miqcli/bin/activate
(miqcli) [rywillia@laptop manageiq-cli]$

# 2. Install the CLI via pip
(miqcli) [rywillia@laptop manageiq-cli]$ pip install -e .

# 3. Change directory to a different one other than the source code
(miqcli) [rywillia@laptop manageiq-cli]$ cd ~

# 4 Run the CLI
(miqcli) [rywillia@laptop ~]$ miqcli
Traceback (most recent call last):
  File "/home/rywillia/miqcli/bin/miqcli", line 6, in <module>
    from miqcli.cli.main import cli
  File "/home/rywillia/github/manageiq-cli/miqcli/cli/main.py", line 26, in <module>
    from miqcli.api import ClientAPI
  File "/home/rywillia/github/manageiq-cli/miqcli/api.py", line 26, in <module>
    from miqcli.constants import AUTHDIR, DEFAULT_CONFIG
  File "/home/rywillia/github/manageiq-cli/miqcli/constants.py", line 29, in <module>
    VERSION = get_version(PACKAGE)
  File "/home/rywillia/miqcli/lib/python2.7/site-packages/pbr/packaging.py", line 755, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name miqcli was given, but was not able to be found.
```

If I switch back to the source code directory everything works fine.

```bash
(miqcli) [rywillia@laptop manageiq-cli]$ miqcli
Usage: miqcli [OPTIONS] COMMAND [ARGS]...

  ManageIQ command line interface.

Options:
  --version                       Show version and exit.
<Truncated>
```

Looks like pbr is unable to get the version based on the order they check for when outside a local copy of the git repository.

**Comment by tehsmyers** [comment]
onooooes

**Comment by tehsmyers** [comment]
The good news is that this only appears to affect editable installs. I also double-checked the pbr api to make sure get_version really is the intended entry point and I still think that's correct.

Workarounds for the immediate breakage:
- `pip install <dir>` (sans `-e` for a "normal" install)
- call `miqcli` from within the source tree.

We can catch that exception and default to '0.0.0' in this case, or potentially use something like "dev", or "unknown". I'm not confident in returning a word, though, since that isn't parseable as a pythonic semantic version string (that I know of).

We could also catch the exception and do something a little nuts, like
```python
wd = os.pwd()
try:
    os.chdir(os.path.dirname(__file__))
    version = get_version(PACKAGE)
finally:
    os.chdir(wd)
```
...so maybe just setting this to `0.0.0` for the specific case of running the cli in an editable version from outside the source tree is fine.

Thoughts?

**Comment by ryankwilliams** [comment]
I was able to reproduce this same behavior when installing without editable option.

```bash
rywillia@laptop ~]$ virtualenv miqcli-test
New python executable in /home/rywillia/miqcli-test/bin/python2
Also creating executable in /home/rywillia/miqcli-test/bin/python
Installing setuptools, pip, wheel...done.
[rywillia@laptop ~]$ source miqcli-test/bin/activate
(miqcli-test) [rywillia@laptop ~]$ cd github/manageiq-cli/
(miqcli-test) [rywillia@laptop manageiq-cli]$ pip install .
Processing /home/rywillia/github/manageiq-cli
Collecting click==6.7 (from miqcli==0.0.1.dev23)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting pbr==3.1.1 (from miqcli==0.0.1.dev23)
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Collecting manageiq_client (from miqcli==0.0.1.dev23)
Collecting PyYAML==3.12 (from miqcli==0.0.1.dev23)
Collecting requests==2.18.4 (from miqcli==0.0.1.dev23)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting wait-for (from manageiq_client->miqcli==0.0.1.dev23)
Collecting six (from manageiq_client->miqcli==0.0.1.dev23)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting simplejson (from manageiq_client->miqcli==0.0.1.dev23)
Collecting iso8601 (from manageiq_client->miqcli==0.0.1.dev23)
  Using cached iso8601-0.1.12-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests==2.18.4->miqcli==0.0.1.dev23)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests==2.18.4->miqcli==0.0.1.dev23)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.18.4->miqcli==0.0.1.dev23)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.18.4->miqcli==0.0.1.dev23)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting parsedatetime (from wait-for->manageiq_client->miqcli==0.0.1.dev23)
  Using cached parsedatetime-2.4-py2-none-any.whl
Collecting future (from parsedatetime->wait-for->manageiq_client->miqcli==0.0.1.dev23)
Building wheels for collected packages: miqcli
  Running setup.py bdist_wheel for miqcli ... done
  Stored in directory: /home/rywillia/.cache/pip/wheels/fa/47/a0/b0df9de1afbc72d53f5cc43b0eca912668ba486e3c2f21c27d
Successfully built miqcli
Installing collected packages: click, pbr, future, parsedatetime, six, wait-for, urllib3, idna, chardet, certifi, requests, simplejson, iso8601, manageiq-client, PyYAML, miqcli
Successfully installed PyYAML-3.12 certifi-2017.11.5 chardet-3.0.4 click-6.7 future-0.16.0 idna-2.6 iso8601-0.1.12 manageiq-client-0.3.0 miqcli-0.0.1.dev23 parsedatetime-2.4 pbr-3.1.1 requests-2.18.4 simplejson-3.13.2 six-1.11.0 urllib3-1.22 wait-for-1.0.9
(miqcli-test) [rywillia@laptop manageiq-cli]$ cd
(miqcli-test) [rywillia@laptop ~]$ miqcli 
Traceback (most recent call last):
  File "/home/rywillia/miqcli-test/bin/miqcli", line 7, in <module>
    from miqcli.cli.main import cli
  File "/home/rywillia/miqcli-test/lib/python2.7/site-packages/miqcli/cli/main.py", line 26, in <module>
    from miqcli.api import ClientAPI
  File "/home/rywillia/miqcli-test/lib/python2.7/site-packages/miqcli/api.py", line 26, in <module>
    from miqcli.constants import AUTHDIR, DEFAULT_CONFIG
  File "/home/rywillia/miqcli-test/lib/python2.7/site-packages/miqcli/constants.py", line 29, in <module>
    VERSION = get_version(PACKAGE)
  File "/home/rywillia/miqcli-test/lib/python2.7/site-packages/pbr/packaging.py", line 755, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name miqcli was given, but was not able to be found.
```

**Comment by tehsmyers** [comment]
This works for both editable and non-editable installs:
```python
>>> import pkg_resources
>>> pkg_resources.get_distribution('miqcli')
miqcli 0.0.1.dev24 (/home/semyers/ve/miqcli/lib/python3.6/site-packages)
```

I suspect I'm just abusing `get_version`. This `get_distribution` call was my first approach, but it didn't work because of a problem in my dev environment that I didn't notice at first. I'll give it another shot and test it with the various failure cases in the issue.
